/**
 * ML queries — investigación no supervisada (2026-05).
 *
 * Reads the JSON exports generated by `ml/scripts/18_export_ml_json.py`.
 * Same synchronous-import pattern as lib/queries.ts to keep the UI simple.
 *
 * The underlying parquets live in `ml/outputs/` (gitignored, regenerable
 * via `python ml/scripts/0X_*.py`). The JSONs are the bridge artifact.
 */

import anomaliasJson from "@/data/ml/ml_anomalias_robustas.json";
import anomaliasHistoricoJson from "@/data/ml/ml_anomalias_robustas_historico.json";
import topProveedoresJson from "@/data/ml/ml_top_proveedores_robustos.json";
import oneshotsJson from "@/data/ml/ml_oneshots_grandes.json";
import estadosRiesgoJson from "@/data/ml/ml_estados_riesgo.json";
import efosPostJson from "@/data/ml/ml_efos_post_presuncion.json";
import continuidadJson from "@/data/ml/ml_continuidad_proveedores.json";
import continuidadPatronesJson from "@/data/ml/ml_continuidad_patrones.json";
import hhiJson from "@/data/ml/ml_hhi_dependencias.json";
import efosTopJson from "@/data/ml/ml_efos_contratos_top.json";
import metaJson from "@/data/ml/ml_meta.json";

import type {
  MlAnomaliaContrato,
  MlAnomaliaContratoHistorico,
  MlOneShot,
  MlEstadoRiesgo,
  MlEfosPostPresuncion,
  MlContinuidadProveedor,
  MlHhiDependencia,
  MlEfosContrato,
  MlMeta,
} from "./types";

export function qMlAnomalias(): MlAnomaliaContrato[] {
  return anomaliasJson as unknown as MlAnomaliaContrato[];
}

export function qMlAnomaliasHistorico(): MlAnomaliaContratoHistorico[] {
  return anomaliasHistoricoJson as unknown as MlAnomaliaContratoHistorico[];
}

export function qMlTopProveedores(): Array<{
  rfc_proveedor: string;
  nombre: string;
  n_contratos_total: number;
  n_contratos_con_flag: number;
  n_contratos_robustos: number;
  monto_total: number;
  monto_con_flag: number;
  flag_efos: boolean;
  score_max: number;
  score_medio: number;
  pct_contratos_con_flag: number;
}> {
  return topProveedoresJson as unknown as ReturnType<typeof qMlTopProveedores>;
}

export function qMlOneShots(): MlOneShot[] {
  return oneshotsJson as unknown as MlOneShot[];
}

export function qMlEstadosRiesgo(): MlEstadoRiesgo[] {
  return estadosRiesgoJson as unknown as MlEstadoRiesgo[];
}

export function qMlEfosPostPresuncion(): MlEfosPostPresuncion[] {
  return efosPostJson as unknown as MlEfosPostPresuncion[];
}

export function qMlContinuidad(): MlContinuidadProveedor[] {
  return continuidadJson as unknown as MlContinuidadProveedor[];
}

export function qMlContinuidadPatrones(): Array<{
  patron_temporal: string;
  n_proveedores: number;
  monto_total: number;
  monto_medio: number;
}> {
  return continuidadPatronesJson as unknown as ReturnType<typeof qMlContinuidadPatrones>;
}

export function qMlHhiDependencias(): MlHhiDependencia[] {
  return hhiJson as unknown as MlHhiDependencia[];
}

export function qMlEfosContratosTop(): MlEfosContrato[] {
  return efosTopJson as unknown as MlEfosContrato[];
}

export function qMlMeta(): MlMeta {
  return metaJson as unknown as MlMeta;
}
